/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package System;

/**
 *
 * @author wj01254
 */
public class Cafe_Menu_System extends javax.swing.JFrame {

    /**
     * Creates new form Cafe_Menu_System
     */
    public Cafe_Menu_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Entree1_Checkbox = new javax.swing.JCheckBox();
        Entree2_Checkbox = new javax.swing.JCheckBox();
        Entree3_Checkbox = new javax.swing.JCheckBox();
        Entree4_Checkbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Entree2_TextField = new javax.swing.JTextField();
        Entree1_TextField = new javax.swing.JTextField();
        Entree3_TextField = new javax.swing.JTextField();
        Entree4_TextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Cost_of_Entrees = new javax.swing.JLabel();
        Cost_of_Snacks = new javax.swing.JLabel();
        Cost_of_Drinks = new javax.swing.JLabel();
        Cost1_TextField = new javax.swing.JTextField();
        Cost2_TextField = new javax.swing.JTextField();
        Cost3_Textfield = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Snack1_Checkbox = new javax.swing.JCheckBox();
        Snack2_Checkbox = new javax.swing.JCheckBox();
        Snack3_Checkbox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Snack1_TextField = new javax.swing.JTextField();
        Snack2_TextField = new javax.swing.JTextField();
        Snack3_Textfield = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        Drink1_Checkbox = new javax.swing.JCheckBox();
        Drink2_Checkbox = new javax.swing.JCheckBox();
        Drink3_Checkbox = new javax.swing.JCheckBox();
        Drink4_Checkbox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        Drink3_TextField = new javax.swing.JTextField();
        Drink2_TextField = new javax.swing.JTextField();
        Drink4_TextField = new javax.swing.JTextField();
        Drink1_TextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Totalbtn = new javax.swing.JButton();
        Recieptbtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Tax = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        Totallabel = new javax.swing.JLabel();
        Tax_Textfield = new javax.swing.JTextField();
        Subtotal_Textfield = new javax.swing.JTextField();
        Total_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 490, 620));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        jLabel1.setText("Cafe Managment Systems");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Entree1_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Entree1_Checkbox.setText("Entree1");

        Entree2_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Entree2_Checkbox.setText("Entree2");

        Entree3_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Entree3_Checkbox.setText("Entree3");

        Entree4_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Entree4_Checkbox.setText("Entree4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel5.setText("Entrees");

        Entree2_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Entree2_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree2_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Entree1_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Entree1_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree1_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Entree3_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Entree3_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree3_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Entree3_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree3_TextFieldActionPerformed(evt);
            }
        });

        Entree4_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Entree4_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree4_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entree3_Checkbox)
                                    .addComponent(Entree4_Checkbox)
                                    .addComponent(Entree2_Checkbox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entree3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Entree4_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Entree2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Entree1_Checkbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Entree1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Entree2_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Entree1_Checkbox)
                                    .addComponent(Entree1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(Entree2_Checkbox)))
                        .addGap(26, 26, 26)
                        .addComponent(Entree3_Checkbox))
                    .addComponent(Entree3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entree4_Checkbox)
                    .addComponent(Entree4_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 370, 340));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Cost_of_Entrees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cost_of_Entrees.setText("Cost of Entrees");

        Cost_of_Snacks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cost_of_Snacks.setText("Cost of Snacks");

        Cost_of_Drinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cost_of_Drinks.setText("Cost of Drinks");

        Cost1_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Cost1_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cost1_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Cost2_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Cost2_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cost2_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Cost3_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Cost3_Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cost3_Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Cost_of_Entrees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(Cost1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Cost_of_Drinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cost3_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Cost_of_Snacks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cost2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cost_of_Entrees)
                    .addComponent(Cost1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cost2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cost_of_Snacks))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cost3_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cost_of_Drinks))
                .addGap(11, 11, 11))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 330, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Snack1_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Snack1_Checkbox.setText("Snack 1");

        Snack2_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Snack2_Checkbox.setText("Snack 2");

        Snack3_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Snack3_Checkbox.setText("Snack 3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Snacks");

        Snack1_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Snack1_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Snack1_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Snack1_TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Snack2_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Snack2_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Snack2_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Snack3_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Snack3_Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Snack3_Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Snack3_Checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Snack3_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Snack2_Checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Snack2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Snack1_Checkbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Snack1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Snack1_Checkbox)
                    .addComponent(Snack1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Snack2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Snack2_Checkbox))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Snack3_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Snack3_Checkbox))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 330, 260));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Drink1_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Drink1_Checkbox.setSelected(true);
        Drink1_Checkbox.setText("Drink 1");
        Drink1_Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drink1_CheckboxActionPerformed(evt);
            }
        });

        Drink2_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Drink2_Checkbox.setText("Drink 2");

        Drink3_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Drink3_Checkbox.setText("Drink 3");

        Drink4_Checkbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Drink4_Checkbox.setText("Drink 4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("Drinks");

        Drink3_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Drink3_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Drink3_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Drink2_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Drink2_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Drink2_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Drink4_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Drink4_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Drink4_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Drink1_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Drink1_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Drink1_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Drink4_Checkbox)
                            .addComponent(Drink3_Checkbox)
                            .addComponent(Drink2_Checkbox)
                            .addComponent(Drink1_Checkbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Drink1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Drink4_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Drink3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Drink2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drink1_Checkbox)
                    .addComponent(Drink1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drink2_Checkbox)
                    .addComponent(Drink2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drink3_Checkbox)
                    .addComponent(Drink3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drink4_Checkbox)
                    .addComponent(Drink4_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 370, 340));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Totalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Totalbtn.setText("Total");
        Totalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalbtnActionPerformed(evt);
            }
        });

        Recieptbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Recieptbtn.setText("Receipt");
        Recieptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecieptbtnActionPerformed(evt);
            }
        });

        Resetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        Exitbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exitbtn.setText("Exit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Totalbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Recieptbtn)
                .addGap(32, 32, 32)
                .addComponent(Resetbtn)
                .addGap(44, 44, 44)
                .addComponent(Exitbtn)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Totalbtn)
                    .addComponent(Recieptbtn)
                    .addComponent(Resetbtn)
                    .addComponent(Exitbtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 770, 490, 100));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tax.setText("Tax");

        SubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubTotal.setText("Subtotal");

        Totallabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Totallabel.setText("Total");

        Tax_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Tax_Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tax_Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Subtotal_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Subtotal_Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Subtotal_Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Total_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Total_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Tax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tax_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Totallabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Total_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(SubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(Subtotal_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tax)
                    .addComponent(Tax_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Subtotal_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Total_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Totallabel))
                .addGap(11, 11, 11))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalbtnActionPerformed

    private void Drink1_CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Drink1_CheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Drink1_CheckboxActionPerformed

    private void Entree3_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree3_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entree3_TextFieldActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
     Cost1_TextField.setText(null);
     Cost2_TextField.setText(null);
     Cost3_Textfield.setText(null);
     Total_TextField.setText(null);
     Subtotal_Textfield.setText(null);
     Tax_Textfield.setText(null);
     Snack3_Textfield.setText(null);
     Snack2_TextField.setText(null);
     Snack1_TextField.setText(null);
     Drink4_TextField.setText(null);
     Drink3_TextField.setText(null);
     Drink2_TextField.setText(null);
     Drink1_TextField.setText(null);
     Entree4_TextField.setText(null);
     Entree3_TextField.setText(null);
     Entree2_TextField.setText(null);
     Entree1_TextField.setText(null);
     
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void RecieptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecieptbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecieptbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Menu_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cost1_TextField;
    private javax.swing.JTextField Cost2_TextField;
    private javax.swing.JTextField Cost3_Textfield;
    private javax.swing.JLabel Cost_of_Drinks;
    private javax.swing.JLabel Cost_of_Entrees;
    private javax.swing.JLabel Cost_of_Snacks;
    private javax.swing.JCheckBox Drink1_Checkbox;
    private javax.swing.JTextField Drink1_TextField;
    private javax.swing.JCheckBox Drink2_Checkbox;
    private javax.swing.JTextField Drink2_TextField;
    private javax.swing.JCheckBox Drink3_Checkbox;
    private javax.swing.JTextField Drink3_TextField;
    private javax.swing.JCheckBox Drink4_Checkbox;
    private javax.swing.JTextField Drink4_TextField;
    private javax.swing.JCheckBox Entree1_Checkbox;
    private javax.swing.JTextField Entree1_TextField;
    private javax.swing.JCheckBox Entree2_Checkbox;
    private javax.swing.JTextField Entree2_TextField;
    private javax.swing.JCheckBox Entree3_Checkbox;
    private javax.swing.JTextField Entree3_TextField;
    private javax.swing.JCheckBox Entree4_Checkbox;
    private javax.swing.JTextField Entree4_TextField;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Recieptbtn;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JCheckBox Snack1_Checkbox;
    private javax.swing.JTextField Snack1_TextField;
    private javax.swing.JCheckBox Snack2_Checkbox;
    private javax.swing.JTextField Snack2_TextField;
    private javax.swing.JCheckBox Snack3_Checkbox;
    private javax.swing.JTextField Snack3_Textfield;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JTextField Subtotal_Textfield;
    private javax.swing.JLabel Tax;
    private javax.swing.JTextField Tax_Textfield;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton Totalbtn;
    private javax.swing.JLabel Totallabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
